import os
import json
from groq import Groq

# Initialize Groq client
# This assumes GROQ_API_KEY is set in the environment (.env)
client = Groq()

def analyze_text(text: str) -> dict:
    """
    Analyzes text using Groq's llama-3.3-70b-versatile model to determine
    if it is human-written or AI-generated.
    
    Returns a dictionary:
    {
        "ai_probability_score": float (0.0 to 1.0, where 1.0 is highest certainty of AI),
        "reasoning": str
    }
    """
    prompt = f"""
You are an expert AI detection system. Analyze the following text and determine if it was likely written by a human or generated by an AI.
Focus on semantic coherence, stylistic patterns, and natural variance.

Respond with a JSON object containing exactly two fields:
1. "ai_probability_score": A float between 0.0 and 1.0, where 1.0 means completely certain it is AI-generated, and 0.0 means completely certain it is human-written. Use decimals to express uncertainty (e.g., 0.85, 0.20, 0.50).
2. "reasoning": A brief explanation of why you gave this score (e.g., mentioning uniform structure, lack of variance, etc.).

Text to analyze:
\"\"\"{text}\"\"\"
"""
    
    try:
        response = client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are a precise JSON-outputting AI detection tool. Do not output anything outside of the JSON block."},
                {"role": "user", "content": prompt}
            ],
            model="llama-3.3-70b-versatile",
            response_format={"type": "json_object"},
            temperature=0.2, # Low temperature for more deterministic scoring
        )
        
        result_content = response.choices[0].message.content
        result_json = json.loads(result_content)
        
        return {
            "llm_score": float(result_json.get("ai_probability_score", 0.5)),
            "llm_reasoning": result_json.get("reasoning", "No reasoning provided")
        }
    except Exception as e:
        print(f"Error in Groq analysis: {e}")
        return {
            "llm_score": 0.5, # Default to uncertain on error
            "llm_reasoning": f"Error during analysis: {str(e)}"
        }

if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()
    
    test_text = "The sun dipped below the horizon, painting the sky in hues of amber and rose. I sat on the porch, coffee in hand, watching the neighborhood slowly go quiet."
    result = analyze_text(test_text)
    print(f"Test Result: {result}")
